# Generated by Django 3.1.3 on 2020-11-22 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.IntegerField(default=None, null=True)),
                ('x', models.IntegerField(default=None, null=True)),
                ('char', models.CharField(default='@', max_length=1)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ground_data', models.TextField()),
                ('solid_data', models.TextField()),
                ('roof_data', models.TextField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_radius', models.IntegerField(default=10)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='networking.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='networking.user')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='networking.room'),
        ),
    ]
