# Generated by Django 3.1.2 on 2020-10-16 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=0)),
                ('char', models.CharField(default='@', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('path', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_radius', models.IntegerField(default=10)),
                ('entityid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='networking.entity')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='networking.user')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='roomid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='networking.room'),
        ),
    ]
