# Generated by Django 3.1.3 on 2020-11-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='name',
            field=models.CharField(default='Entity', max_length=50),
            preserve_default=False,
        ),
    ]
