# Generated by Django 3.1.3 on 2020-11-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0002_entity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='x',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='y',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
