# Generated by Django 3.1.3 on 2020-11-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0003_auto_20201121_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='roomid',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='entityid',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='userid',
            new_name='user',
        ),
    ]
