# This is a basic workflow to help you get started with Actions

name: Deploy MoonlapseMUD on production server

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master

    # Pulls the changes to master on the remote host
    - name: Stop the currently running server
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        script: |
          tmux kill-session -t gameserver
          cd ${{ secrets.REMOTE_GAME_DIR }}
          git stash
          git pull origin master
          git stash pop
          python3 ${{ secrets.REMOTE_GAME_DIR }}/server/manage.py makemigrations server
          python3 ${{ secrets.REMOTE_GAME_DIR }}/server/manage.py migrate
          tmux new-session -d -s gameserver \; send-keys "python3 ${{ secrets.REMOTE_GAME_DIR }}/server" Enter
          exit
